[book]
authors = ["Colin Roberts, Waylon Jepsen", "Dragan Rakita"]
language = "en"
multilingual = false
src = "documentation/src"
title = "Rust EVM"

[output.linkcheck]
optional = true
follow-web-links = true
